// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Firstname            string   `protobuf:"bytes,2,opt,name=firstname,proto3" json:"firstname,omitempty"`
	Lastname             string   `protobuf:"bytes,3,opt,name=lastname,proto3" json:"lastname,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Role                 string   `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	Verificationid       string   `protobuf:"bytes,7,opt,name=verificationid,proto3" json:"verificationid,omitempty"`
	Verified             bool     `protobuf:"varint,8,opt,name=verified,proto3" json:"verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetFirstname() string {
	if m != nil {
		return m.Firstname
	}
	return ""
}

func (m *User) GetLastname() string {
	if m != nil {
		return m.Lastname
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetVerificationid() string {
	if m != nil {
		return m.Verificationid
	}
	return ""
}

func (m *User) GetVerified() bool {
	if m != nil {
		return m.Verified
	}
	return false
}

type CreateUserResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}
func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (dst *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(dst, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type LoginResponse struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}
func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (dst *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(dst, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "User")
	proto.RegisterType((*CreateUserResponse)(nil), "CreateUserResponse")
	proto.RegisterType((*LoginResponse)(nil), "LoginResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginResponse, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *User, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *User, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/UserService/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	CreateUser(context.Context, *User) (*CreateUserResponse, error)
	Login(context.Context, *User) (*LoginResponse, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UserService/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user.proto",
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x51, 0xc1, 0x4e, 0x32, 0x31,
	0x10, 0x4e, 0x81, 0xe5, 0x87, 0xf9, 0x03, 0x21, 0x23, 0x26, 0x0d, 0x72, 0x20, 0x4d, 0x24, 0x84,
	0xc3, 0x12, 0xf5, 0x62, 0xb8, 0x1a, 0x6f, 0x9e, 0x30, 0x3e, 0x40, 0x85, 0x61, 0xd3, 0xb8, 0xb4,
	0x9b, 0xb6, 0xe2, 0xdd, 0x07, 0xf0, 0xe2, 0xa3, 0xf9, 0x0a, 0xc6, 0xe7, 0x30, 0xed, 0xb2, 0x4b,
	0xd4, 0x53, 0xfb, 0x7d, 0xdf, 0x7c, 0xdf, 0xcc, 0x64, 0x00, 0x9e, 0x1d, 0xd9, 0xb4, 0xb0, 0xc6,
	0x9b, 0xd1, 0x38, 0x33, 0x26, 0xcb, 0x69, 0x21, 0x0b, 0xb5, 0x90, 0x5a, 0x1b, 0x2f, 0xbd, 0x32,
	0xda, 0x95, 0xaa, 0xf8, 0x62, 0xd0, 0x7a, 0x70, 0x64, 0x71, 0x04, 0x9d, 0x60, 0xd2, 0x72, 0x47,
	0x9c, 0x4d, 0xd8, 0xac, 0xbb, 0xaa, 0x31, 0x8e, 0xa1, 0xbb, 0x55, 0xd6, 0xf9, 0x28, 0x36, 0xa2,
	0x78, 0x24, 0x82, 0x33, 0x97, 0x07, 0xb1, 0x59, 0x3a, 0x2b, 0x8c, 0x43, 0x48, 0x68, 0x27, 0x55,
	0xce, 0x5b, 0x51, 0x28, 0x41, 0x70, 0x14, 0xd2, 0xb9, 0x17, 0x63, 0x37, 0x3c, 0x29, 0x1d, 0x15,
	0x46, 0x84, 0x96, 0x35, 0x39, 0xf1, 0x76, 0xe4, 0xe3, 0x1f, 0xa7, 0xd0, 0xdf, 0x93, 0x55, 0x5b,
	0xb5, 0x8e, 0xb3, 0xab, 0x0d, 0xff, 0x17, 0xd5, 0x5f, 0x6c, 0xc8, 0x2d, 0x19, 0xda, 0xf0, 0xce,
	0x84, 0xcd, 0x3a, 0xab, 0x1a, 0x8b, 0x29, 0xe0, 0x8d, 0x25, 0xe9, 0x29, 0x6c, 0xbb, 0x22, 0x57,
	0x18, 0xed, 0x08, 0x07, 0xd0, 0xdc, 0xb9, 0xec, 0xb0, 0x70, 0xf8, 0x8a, 0x73, 0xe8, 0xdd, 0x99,
	0x4c, 0xe9, 0xba, 0x64, 0x08, 0x89, 0x37, 0x4f, 0xa4, 0x0f, 0x45, 0x25, 0xb8, 0x7c, 0x63, 0xf0,
	0x3f, 0x24, 0xdd, 0x93, 0xdd, 0xab, 0x35, 0xe1, 0x2d, 0xc0, 0x31, 0x1e, 0x93, 0x34, 0x3c, 0xa3,
	0x93, 0xf4, 0x6f, 0x4b, 0x71, 0xf6, 0xfa, 0xf1, 0xf9, 0xde, 0x38, 0x15, 0x83, 0x78, 0x91, 0xfd,
	0xc5, 0xc2, 0x52, 0xa6, 0x9c, 0x27, 0xbb, 0x64, 0x73, 0xbc, 0x86, 0x24, 0x76, 0xaf, 0x12, 0xfa,
	0xe9, 0x8f, 0x61, 0x04, 0x8f, 0x66, 0x14, 0xbd, 0xca, 0x9c, 0x07, 0x79, 0xc9, 0xe6, 0x8f, 0xed,
	0x78, 0xcf, 0xab, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0xfd, 0x93, 0x89, 0x55, 0xfb, 0x01, 0x00,
	0x00,
}
