// Code generated by protoc-gen-go. DO NOT EDIT.
// source: train.proto

package train

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Train struct {
	Brandname            string   `protobuf:"bytes,1,opt,name=brandname,proto3" json:"brandname,omitempty"`
	Brandlogo            string   `protobuf:"bytes,2,opt,name=brandlogo,proto3" json:"brandlogo,omitempty"`
	Brandfeatures        string   `protobuf:"bytes,3,opt,name=brandfeatures,proto3" json:"brandfeatures,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Train) Reset()         { *m = Train{} }
func (m *Train) String() string { return proto.CompactTextString(m) }
func (*Train) ProtoMessage()    {}
func (*Train) Descriptor() ([]byte, []int) {
	return fileDescriptor_9befe41711f93460, []int{0}
}
func (m *Train) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Train.Unmarshal(m, b)
}
func (m *Train) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Train.Marshal(b, m, deterministic)
}
func (dst *Train) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Train.Merge(dst, src)
}
func (m *Train) XXX_Size() int {
	return xxx_messageInfo_Train.Size(m)
}
func (m *Train) XXX_DiscardUnknown() {
	xxx_messageInfo_Train.DiscardUnknown(m)
}

var xxx_messageInfo_Train proto.InternalMessageInfo

func (m *Train) GetBrandname() string {
	if m != nil {
		return m.Brandname
	}
	return ""
}

func (m *Train) GetBrandlogo() string {
	if m != nil {
		return m.Brandlogo
	}
	return ""
}

func (m *Train) GetBrandfeatures() string {
	if m != nil {
		return m.Brandfeatures
	}
	return ""
}

type CreateTrainResponse struct {
	Msg                  string   `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateTrainResponse) Reset()         { *m = CreateTrainResponse{} }
func (m *CreateTrainResponse) String() string { return proto.CompactTextString(m) }
func (*CreateTrainResponse) ProtoMessage()    {}
func (*CreateTrainResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9befe41711f93460, []int{1}
}
func (m *CreateTrainResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateTrainResponse.Unmarshal(m, b)
}
func (m *CreateTrainResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateTrainResponse.Marshal(b, m, deterministic)
}
func (dst *CreateTrainResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateTrainResponse.Merge(dst, src)
}
func (m *CreateTrainResponse) XXX_Size() int {
	return xxx_messageInfo_CreateTrainResponse.Size(m)
}
func (m *CreateTrainResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateTrainResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateTrainResponse proto.InternalMessageInfo

func (m *CreateTrainResponse) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Train)(nil), "Train")
	proto.RegisterType((*CreateTrainResponse)(nil), "CreateTrainResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// TrainServiceClient is the client API for TrainService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TrainServiceClient interface {
	CreateTrain(ctx context.Context, in *Train, opts ...grpc.CallOption) (*CreateTrainResponse, error)
}

type trainServiceClient struct {
	cc *grpc.ClientConn
}

func NewTrainServiceClient(cc *grpc.ClientConn) TrainServiceClient {
	return &trainServiceClient{cc}
}

func (c *trainServiceClient) CreateTrain(ctx context.Context, in *Train, opts ...grpc.CallOption) (*CreateTrainResponse, error) {
	out := new(CreateTrainResponse)
	err := c.cc.Invoke(ctx, "/TrainService/CreateTrain", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TrainServiceServer is the server API for TrainService service.
type TrainServiceServer interface {
	CreateTrain(context.Context, *Train) (*CreateTrainResponse, error)
}

func RegisterTrainServiceServer(s *grpc.Server, srv TrainServiceServer) {
	s.RegisterService(&_TrainService_serviceDesc, srv)
}

func _TrainService_CreateTrain_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Train)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TrainServiceServer).CreateTrain(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/TrainService/CreateTrain",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TrainServiceServer).CreateTrain(ctx, req.(*Train))
	}
	return interceptor(ctx, in, info, handler)
}

var _TrainService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "TrainService",
	HandlerType: (*TrainServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTrain",
			Handler:    _TrainService_CreateTrain_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "train.proto",
}

func init() { proto.RegisterFile("train.proto", fileDescriptor_9befe41711f93460) }

var fileDescriptor_9befe41711f93460 = []byte{
	// 210 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x29, 0x4a, 0xcc,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x97, 0x92, 0x49, 0xcf, 0xcf, 0x4f, 0xcf, 0x49, 0xd5,
	0x4f, 0x2c, 0xc8, 0xd4, 0x4f, 0xcc, 0xcb, 0xcb, 0x2f, 0x49, 0x2c, 0xc9, 0xcc, 0xcf, 0x2b, 0x86,
	0xc8, 0x2a, 0x65, 0x72, 0xb1, 0x86, 0x80, 0x14, 0x0b, 0xc9, 0x70, 0x71, 0x26, 0x15, 0x25, 0xe6,
	0xa5, 0xe4, 0x25, 0xe6, 0xa6, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x04, 0xe0, 0xb2,
	0x39, 0xf9, 0xe9, 0xf9, 0x12, 0x4c, 0x48, 0xb2, 0x20, 0x01, 0x21, 0x15, 0x2e, 0x5e, 0x30, 0x27,
	0x2d, 0x35, 0xb1, 0xa4, 0xb4, 0x28, 0xb5, 0x58, 0x82, 0x19, 0xac, 0x02, 0x55, 0x50, 0x49, 0x9d,
	0x4b, 0xd8, 0xb9, 0x28, 0x35, 0xb1, 0x24, 0x15, 0x6c, 0x61, 0x50, 0x6a, 0x71, 0x41, 0x7e, 0x5e,
	0x71, 0xaa, 0x90, 0x00, 0x17, 0x73, 0x6e, 0x71, 0x3a, 0xd4, 0x4a, 0x10, 0xd3, 0x28, 0x94, 0x8b,
	0x07, 0xac, 0x24, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x95, 0x8b, 0x1b, 0x49, 0xa3,
	0x10, 0x9b, 0x1e, 0x98, 0x96, 0x12, 0xd1, 0xc3, 0x62, 0x9c, 0x92, 0x44, 0xd3, 0xe5, 0x27, 0x93,
	0x99, 0x84, 0x94, 0x78, 0xc1, 0x1e, 0x2e, 0x33, 0xd4, 0x07, 0x87, 0x85, 0x15, 0xa3, 0x56, 0x12,
	0x1b, 0xd8, 0xc7, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x59, 0x95, 0xc4, 0x1e, 0x01,
	0x00, 0x00,
}
